# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-27 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppToDo', '0002_auto_20190625_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='item',
        ),
        migrations.AddField(
            model_name='list',
            name='task',
            field=models.CharField(default='task', max_length=50),
        ),
    ]
