# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-27 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppToDo', '0003_auto_20190626_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='task',
        ),
        migrations.AddField(
            model_name='list',
            name='item',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
