# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-01 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppToDo', '0004_auto_20190626_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='item',
            field=models.CharField(max_length=75),
        ),
    ]
